import { AppState } from './types';

export const APP_UPDATES = [
  { 
    version: '3.0', 
    date: '01/05/2026', 
    desc: 'Mise à jour Majeure v3.0 🚀 :\n- Introduction des Fils de discussion (Threads) dans les groupes.\n- Nouveau bouton "Tout télécharger" pour les messages avec fichiers.\n- DJ Bot migré en mode SMS privé pour une assistance personnelle.\n- Paramètres personnalisés avec sauvegarde automatique (Couleur, Notifications).\n- Sidebar intelligente (Auto-hide et Layout fluide).\n- Amélioration de la sécurité et de la gestion Admin/Staff.\n- Corrections majeures sur la sélection multiple et les discussions épinglées.',
    manual: '### Guide d\'utilisation v3.0\n\n1. **Fils de discussion** : Appuyez sur l\'icône de boucle à gauche d\'un message pour créer un fil. Donnez-lui un nom et discutez de manière isolée !\n2. **Téléchargements** : Pour les messages contenant plusieurs fichiers, un bouton "Tout télécharger" apparaît désormais en haut de la bulle.\n3. **DJ Bot** : Retrouvez DJ Bot dans vos SMS (onglet SMS) pour poser vos questions en toute discrétion.\n4. **Personnalisation** : Allez dans Paramètres pour changer la couleur de l\'app. C\'est sauvegardé instantanément.\n5. **Admin & Sécurité** : Les outils de modération ont été renforcés pour garantir une communauté saine.'
  },
  { version: '3.0.0', date: '21/04/2026', desc: 'Mise à jour v3.0 Stabilité & Ergonomie : Mode Sombre implémenté. Mises à jour intelligentes (l\'auto-actualisation attend désormais que vous ayez envoyé votre brouillon en cours pour ne rien effacer). Menu mobile 100% écran. Correction des espaces vides sur grand écran. Actions message (supprimer, sélectionner, muter) disposées horizontalement de droite à gauche avec de toutes nouvelles infobulles. Suppression intégrale rétablie : supprimer un SMS ou un groupe supprime désormais formellement *tous* les messages du serveur de façon irréversible. Correction visibilité globale des textes de saisie dans toute l\'application (mode clair fluide). Optimisation de tous les paramètres : boutons de confirmation discrets.' },
  { version: '2.9.9', date: '19/04/2026', desc: 'Optimisation Layout Mobile : Le menu latéral repousse désormais le contenu au lieu de l\'écraser, garantissant une lisibilité parfaite sur petit écran. Unification totale de l\'interface entre mobile et PC, avec suppression des effets de flou pour une meilleure clarté visuelle.' },
  { version: '2.9.8', date: '19/04/2026', desc: 'Interface unifiée et Profils : Le menu latéral divise désormais l\'écran sans superposition. Un nouveau système de profil universel "Style DJ" est accessible en cliquant sur n\'importe quel avatar ou nom d\'utilisateur (Voir photo ou SMS direct).' },
  { version: '2.9.7', date: '19/04/2026', desc: 'Stabilité et corrections ultimes : Les SMS supprimés ne disparaissent plus chez votre interlocuteur. Les notifications locales sont désormais intelligentes et regroupent vos messages non lus. Enfin, le système de déploiement des mises à jour PWA passe en natif pour une réactivité immédiate sans cache.' },
  { version: '2.9.6', date: '19/04/2026', desc: 'Gestion avancée de la suppression des messages : Tout le monde peut masquer un message "Pour soi". Les Admins/Sous-Admins peuvent supprimer un message "Pour tous" dans leur groupe. Le Staff a un pouvoir de suppression définitive de la bulle ! Ajout de la suppression en lot avec sélection multiple. De plus, la nomination et révocation des sous-admins est réparée.' },
  { version: '2.9.5', date: '19/04/2026', desc: 'Interface Améliorée : Nouveau menu latéral fixe sur PC pour une navigation fluide en 2 colonnes. Ajout d\'une fenêtre de profil universelle (style DJ) au clic sur n\'importe quel avatar/nom pour voir la photo ou envoyer un SMS direct. C\'est aussi ce nouveau système d\'affichage des mises à jour avec bouton Détail !' },
  { version: '2.9.4', date: '15/04/2026', desc: 'Réparation complète du système de notifications (PWA et navigateur) et de l\'indicateur de nouveaux messages. Ajout d\'un bouton "Tout marquer comme lu" dans les discussions. Les messages non lus ne restent plus bloqués.' },
  { version: '2.9.3', date: '14/04/2026', desc: 'Améliorations majeures : Envoi de multiples fichiers en même temps (jusqu\'à 200 Mo), support des fichiers Microsoft (Word, Excel), des archives (.zip, .rar) et des fichiers de code (.html, .js, etc.). Gestion complète des sous-admins dans les groupes privés. Possibilité de modifier l\'icône pour tous les types de groupes. Correction de l\'affichage des icônes de groupe et du défilement dans les paramètres.' },
  { version: '2.9.2', date: '14/04/2026', desc: 'Correction de l\'erreur BloomFilter et améliorations de stabilité.' },
  { version: '2.9.1', date: '14/04/2026', desc: 'Nouveau système de mise à jour automatique : Détection instantanée des nouvelles versions et réactualisation intelligente lors de l\'entrée dans l\'application.' },
  { version: '2.9.0', date: '13/04/2026', desc: 'Gestion avancée des groupes : Liste des membres en privé, filtrage Admin/Sous-Admins en public. Système de bannissement temporaire (3 semaines) avec limite de 5 fois. Permissions étendues pour les Sous-Admins. Suppression des messages via menu 3 points mis en évidence. Suppression des discussions vides. Révélation des messages supprimés pour Super Admins.' },
  { version: '2.8.0', date: '13/04/2026', desc: 'Support multi-fichiers : Envoi d\'audio, PDF, DOCX et fichiers application (.apk, .exe). Synchronisation des paramètres sur tous les appareils. Correction des paramètres par défaut.' },
  { version: '2.7.0', date: '13/04/2026', desc: 'Nouveau système de sauvegarde des paramètres avec confirmation. Correction du DJ Bot (icône et réponses). Optimisation de la rotation des astuces (toutes les 10 min). Correction de l\'erreur de profil (URL trop longue).' },
  { version: '2.6.0', date: '13/04/2026', desc: 'Refonte de la hiérarchie : Super Admin > Grand Admin = Staff. Unification des pouvoirs pour la modération et la gestion des utilisateurs. Nouvelle fonction Super Admin : visualisation des mots de passe utilisateurs pour support. Activation par défaut du masquage automatique du menu. Optimisation majeure de l\'espacement des bulles de message.' },
  { version: '2.5.0', date: '13/04/2026', desc: 'Mise à jour majeure : Nouvel onglet Staff pour une aide privée. Hiérarchie des rôles renforcée (Grand Admin > Super Admin > Staff). Masquage des IDs utilisateurs. Optimisation responsive pour PC, Tablettes et Smart TV. Retour de la discussion SMS avec DJ Bot. Mode Secret pour les Admins/Staff dans les groupes privés. Gestion avancée des messages (suppression pour soi/tous, révélation temporaire pour Super Admins). Rôles de groupe (Admin/Sous-Admins). Mode paysage activé pour PWA.' },
  { version: '2.4.0', date: '12/04/2026', desc: 'Intégration Cloudinary : Support des fichiers jusqu\'à 100 Mo with stockage intelligent (Cloudinary pour le lourd, Firebase pour le léger). Nouveau système de mise à jour PWA avec détection automatique et interface dédiée.' },
  { version: '2.3.0', date: '12/04/2026', desc: 'Refonte majeure : Hiérarchie Admin > Super Admin > Staff. Nouvel onglet Discussions avec mini-onglets (Publics, Privés, SMS). Création de groupe en 4 étapes avec progression. Mode Test en lecture seule pour les groupes publics. Nouvel onglet Amis avec recherche. DJ Bot limité à 5 questions/jour.' },
  { version: '2.2.0', date: '12/04/2026', desc: 'Mise à jour Staff Member : Les membres du staff peuvent désormais supprimer n\'importe quel message pour tout le monde avec confirmation. Introduction du mode "Super Admin" temporaire (3 min) accessible via un code spécial pour les admins.' },
  { version: '2.1.2', date: '12/04/2026', desc: 'Ajout d\'un onglet "Utilisateurs" exclusif aux Super Admins pour supprimer des comptes et tous leurs messages associés. Ajout d\'un bouton "Retour" fonctionnel dans les discussions.' },
  { version: '2.1.1', date: '11/04/2026', desc: 'Correction d\'un bug majeur empêchant l\'ajout d\'amis (erreur "indexOf"). Correction d\'un crash lié à l\'affichage des avatars (erreur "0").' },
  { version: '2.1.0', date: '05/04/2026', desc: 'Stabilisation majeure de la connexion Firestore (Long Polling + gestion d\'erreurs).' },
  { version: '2.0.0', date: '01/04/2026', desc: 'Refonte majeure des discussions : sous-onglets Publics, Privés et SMS. Nouveau système de création de groupe par étapes.' },
  { version: '1.2.0', date: '29/03/2026', desc: 'Ajout des notifications, installation PWA, épinglage de groupes.' },
  { version: '1.1.0', date: '28/03/2026', desc: 'Ajout des groupes privés, profils, amis et DJ Society.' },
  { version: '1.0.0', date: '28/03/2026', desc: 'Création de DJ Messenger. Chat public et authentification de base.' }
];
